language: haskell

ghc:
  - 7.0.4
  - 7.4.2
  - 7.6.3
  - 7.8.4

install:
  - cabal update
  - cabal install . example/ -j --only-dependencies

script:
  - cabal configure
  - cabal build
  - ( cd example/ ; cabal configure ; cabal build )
