language: haskell

ghc:
  - 7.4.2
  - 7.6.3
  - 7.8.4

before_install:
  - export GHCVER=`ghc --numeric-version`

install:
  - cabal update
  - cabal install -j --only-dependencies

script:
  - cabal configure
  - cabal build
  - cabal install
  - |
    if [ $GHCVER != "7.4.2" ]; then
      ( cd example/ ; cabal install -j --only-dependencies ; cabal configure ; cabal build )
    fi
